// Crypto-extension + CRC32 gadgets: SHA512H/H2/SU0/SU1 (including an
// rd==rn aliasing case), the SHA3 ops RAX1/EOR3/BCAX/XAR (synthesized
// from baseline NEON in crypto.S), and CRC32/CRC32C. Expected values were
// generated by the native instructions on M-series hardware (genvec, see
// git history of this file's introduction). Run twice: plain (native
// gadget path on capable hosts) and with ISH_ARM64_FORCE_SOFT_CRYPTO=1
// (the pre-A13/pre-A10 soft C fallbacks — the sshd-under-lldb
// EXC_BAD_INSTRUCTION crash on A10, where the sha512su0 gadget executed
// an instruction the host doesn't have). Scaffolding sticks to
// JIT-implemented transfers: LDR (literal, GPR), FMOV general->D,
// INS general->element, UMOV — no SIMD literal loads or vector MOV.
// Expected: exits 0; non-zero = number of the first failed check.
.arch_extension sha2
.arch_extension sha3
.arch_extension crc
.global _start
.text

// Reset v4 = D (the accumulator input) from x21/x22.
.macro loadd
    fmov d4, x21
    mov v4.d[1], x22
.endm

// Compare v4 against a 128-bit expected value.
.macro checkv lo, hi
    fmov x1, d4
    ldr x2, =\lo
    cmp x1, x2
    b.ne fail
    mov x1, v4.d[1]
    ldr x2, =\hi
    cmp x1, x2
    b.ne fail
.endm

_start:
    // Operands (same vectors genvec.c fed the hardware):
    // x21:x22 = D; v1 = N, v2 = M
    ldr x21, =0x0123456789abcdef
    ldr x22, =0xfedcba9876543210
    ldr x3, =0x02468ace13579bdf
    fmov d1, x3
    ldr x3, =0xf13579bdf02468ac
    mov v1.d[1], x3
    ldr x3, =0xdeadbeefcafebabe
    fmov d2, x3
    ldr x3, =0x0f1e2d3c4b5a6978
    mov v2.d[1], x3

    movz x27, #1              // 1: SHA512SU0
    loadd
    sha512su0 v4.2d, v1.2d
    checkv 0x6f907deb1d5cb34d, 0x5d024990d1f26753

    add x27, x27, #1          // 2: SHA512H
    loadd
    sha512h q4, q1, v2.2d
    checkv 0x68574c0b37182263, 0x929fa5b1ad83ec95

    add x27, x27, #1          // 3: SHA512H2
    loadd
    sha512h2 q4, q1, v2.2d
    checkv 0xbc3a2a2f9ca8cfd9, 0x8fad61bde280c848

    add x27, x27, #1          // 4: SHA512SU1
    loadd
    sha512su1 v4.2d, v1.2d, v2.2d
    checkv 0xc117b06ac852cbaa, 0x15756e049b830649

    add x27, x27, #1          // 5: SHA512H with rd==rn (aliasing: operands
    loadd                     //    must be read before rd is written)
    sha512h q4, q4, v2.2d
    checkv 0x8379bdcbdf1db823, 0x923ae4c8371c3e21

    add x27, x27, #1          // 6: RAX1
    rax1 v4.2d, v1.2d, v2.2d
    checkv 0xbf1df71186aaeea2, 0xef0923c56690ba5c

    add x27, x27, #1          // 7: EOR3
    loadd                     // v4 = D (first source, not accumulator)
    eor3 v5.16b, v4.16b, v1.16b, v2.16b
    fmov x1, d5
    ldr x2, =0xddc871465002ec8e
    cmp x1, x2
    b.ne fail
    mov x1, v5.d[1]
    ldr x2, =0x00f7ee19cd2a33c4
    cmp x1, x2
    b.ne fail

    add x27, x27, #1          // 8: BCAX
    loadd
    bcax v5.16b, v4.16b, v1.16b, v2.16b
    fmov x1, d5
    ldr x2, =0x0161456798aaccae
    cmp x1, x2
    b.ne fail
    mov x1, v5.d[1]
    ldr x2, =0x0efdea19c6703294
    cmp x1, x2
    b.ne fail

    add x27, x27, #1          // 9: XAR #13
    xar v4.2d, v1.2d, v2.2d, #13
    checkv 0x0b0ee759a10ecd49, 0x0ea7f15aa40ddbf0

    // CRC32: acc = 0x12345678, value = 0x1122334455667788
    ldr w5, =0x12345678
    ldr x6, =0x1122334455667788

    add x27, x27, #1          // 10: CRC32B
    crc32b w7, w5, w6
    ldr w8, =0xbdafc64a
    cmp w7, w8
    b.ne fail

    add x27, x27, #1          // 11: CRC32H
    crc32h w7, w5, w6
    ldr w8, =0x58d5e3d7
    cmp w7, w8
    b.ne fail

    add x27, x27, #1          // 12: CRC32W
    crc32w w7, w5, w6
    ldr w8, =0xdfdcd195
    cmp w7, w8
    b.ne fail

    add x27, x27, #1          // 13: CRC32X
    crc32x w7, w5, x6
    ldr w8, =0xc26df9b6
    cmp w7, w8
    b.ne fail

    add x27, x27, #1          // 14: CRC32CB
    crc32cb w7, w5, w6
    ldr w8, =0xf37c5b23
    cmp w7, w8
    b.ne fail

    add x27, x27, #1          // 15: CRC32CX
    crc32cx w7, w5, x6
    ldr w8, =0x693b8e8b
    cmp w7, w8
    b.ne fail

    movz x0, #0
    movz x8, #93
    svc #0
fail:
    mov x0, x27
    movz x8, #93
    svc #0

.pool
